name: Byron
favicon: null
layout_spectrum: 0.12022140412591398
typography_spectrum: 0.7610344418790191
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#393735'
    - '#7b7675'
    - '#999795'
    - '#dad9d7'
  brandStrength: 0.373161161551252
  lightness: 0.8495115153491497
  saturation: 0.06439020810648799
  rhythmicContrast: 0.5946999690495431
purpose: []
